// Generated by CoffeeScript 1.12.4
var NamedFunction, Validator, ValidatorType, define, setKind, setType, steal;

NamedFunction = require("NamedFunction");

setKind = require("setKind");

setType = require("setType");

steal = require("steal");

Validator = require("./Validator");

define = Object.defineProperty;

ValidatorType = NamedFunction("ValidatorType", function(name, config) {
  var displayName, init, key, type, value;
  init = steal(config, "init");
  displayName = steal(config, "name");
  type = NamedFunction(name, function() {
    var self;
    self = Validator(displayName);
    init && init.apply(self, arguments);
    return setType(self, type);
  });
  for (key in config) {
    value = config[key];
    define(type.prototype, key, {
      value: value,
      configurable: true
    });
  }
  setKind(type, Validator);
  return setType(type, ValidatorType);
});

module.exports = setKind(ValidatorType, Function);
