// Generated by CoffeeScript 1.11.1
var define, isDev, mergeDefaults;

isDev = require("isDev");

define = Object.defineProperty;

mergeDefaults = function(obj, defaults) {
  var key, value;
  for (key in defaults) {
    value = defaults[key];
    if (obj[key] !== void 0) {
      continue;
    }
    if (isDev && key.startsWith("_")) {
      define(obj, key, {
        value: value,
        writable: true,
        configurable: true
      });
    } else {
      obj[key] = value;
    }
  }
};

module.exports = mergeDefaults;
